import type { components } from './generated/minilith';

export type Activity = components['schemas']['Activity'];
export type ActivityHostInvite = components['schemas']['ActivityHostInvite'];
export type BriefActivity = components['schemas']['BriefActivity'];
export type PutActivity = components['schemas']['PutActivity'];
export type ReportRequest = components['schemas']['ReportRequest'];
export type ExternalSaleCategory = components['schemas']['ExternalSaleCategory'];
export type ActivityTicketKind = components['schemas']['ActivityTicketKind'];
export type TicketKind = components['schemas']['Kind'];
export type PutTicketKind = components['schemas']['PutTicketKind'];
export type PutNotification = components['schemas']['PutNotification'];
export type ActivityNotification = components['schemas']['ActivityNotification'];
export type PutActivityNotification = components['schemas']['PutActivityNotification'];
export type ActivityNotificationKind = components['schemas']['ActivityNotificationKind'];
export type GroupNotification = components['schemas']['GroupNotification'];
export type PurchasedTicket = components['schemas']['AdminPurchasedTicket'];
export type AdminUser = components['schemas']['AdminUser'];
export type Group = components['schemas']['Group'];
export type PutGroup = components['schemas']['PutGroup'];
export type Me = components['schemas']['Me'];
export type UploadAllowance = components['schemas']['ObjectUploadAllowanceResponse'];
